### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by rubyFeedback** [mvz/gir_ffi#320]
Hey there Matijs,

Unless I installed the wrong gem or repository, the /gir_ffi/examples/
directory contains only two .rb files. Perhaps other examples exist
but they did not seem to be part of this repository.

The two files are clutter.rb and main_loop.rb.

If you ever have time and are motivated, could you add a few SIMPLE
examples?

- One hello world in gir_ffi (gtk3 suffices)
- Ideally also one gtk-entry, one gtk-button ... hmm. That's it probably.

If you don't want to create too many examples then perhaps one
"meta" or "complex" example similar to libui:

https://github.com/kojix2/LibUI/blob/main/examples/control_gallery.rb

This would help people get adjusted to gir_ffi more quickly if they
can tweak existing examples that are proven to work (because you
probably understand the code base best, and know how to work
with it).

**Comment by mvz** [comment]
Hi @rubyFeedback you can find more Gtk related examples here: https://github.com/mvz/gir_ffi-gtk/tree/master/examples.
