### ISSUE TITLE
gir_ffi and vte

### ISSUE THREAD

**Issue by cedlemo** [mvz/gir_ffi#65]
I try to use the Vte lib with gir_ffi but I don't really know how it works. Here is what I have now:

```ruby
require 'gir_ffi'
require 'gir_ffi-gtk3'
GirFFI.setup :Vte, '2.91'
GirFFI.setup :Gio
Gtk.init
win = Gtk::Window.new :toplevel
win.show

term = Vte::Terminal.new
command_array = GLib.shell_parse_argv("/usr/bin/bash")

spawn_sync(0,#Vte::PtyFlags::DEFAULT,
           "/home/cedlemo",
           command_array,
           [],
           GLib::SpawnFlags::SEARCH_PATH)
  
win.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```

I am stuck with those : 
*    Vte::PtyFlags (Module exists but have no usable constants)
*    GLib::SpawnFlags can not be found 

I have some difficulties to understand how to use the command_array value : 

```ruby
command_array = GLib.shell_parse_argv("/usr/bin/bash") # => Array
command_array[0] # true
command_array[1] #<GLib::Strv:0x0000000242b880>
```

Thanks

**Comment by mvz** [comment]
Hi @cedlemo,

GirFFI does not turn GLib's enum values into constants, but instead uses symbols. So instdead of `Vte::PtyFlags::DEFAULT`, you would just put `:default`, and for `GLib::SpawnFlags::SEARCH_PATH` you would put `:search_path`.

`GLib.shell_parse_arg` returns a pair of values, because the underlying C function has a return value (a boolean indicating success), and a pair of output parameters (argcp and argvp) that together represent an array of arguments. TL;DR: You need to pass the second value to `spawn_sync`.

I'm unable to get `spawn_sync` itself to work at the moment, I'll get back to you on that.

**Comment by mvz** [comment]
The following works for me. There's something odd going on with the arguments for `spawn_sync`. Ideally, you should be able to just pass `nil` instead of the `proc` I use, but the `nil` for the `user_data` is not properly converted to a `NULL` by GirFFI.

```ruby
require 'gir_ffi'
require 'gir_ffi-gtk3'
GirFFI.setup :Vte, '2.91'
GirFFI.setup :Gio
Gtk.init
win = Gtk::Window.new :toplevel
term = Vte::Terminal.new

# The terminal must be added to the window so it will be shown
win.add term
# Shows the window and the terminal
win.show_all
win.signal_connect("destroy") { Gtk.main_quit }

result, command_array = GLib.shell_parse_argv("/bin/bash")

# spawn_sync won't return so we run it in a separate thread
Thread.new {
  result, pid = term.spawn_sync(:default,
                                "/home/matijs",
                                command_array,
                                [],
                                :search_path,
                                proc { }, # An empty proc must be passed, because ...
                                nil,      # ... this user data is not passed as NULL
                                nil)
}

Gtk.main
```

**Comment by cedlemo** [comment]
Why have you used the `spawn_sync` in a thread, is it a specific requirement for gir_ffi-gtk3 ?

**Comment by cedlemo** [comment]
sorry I didn't read the comment, Ok thanks a lot.

Do you need some examples (I did one for the Gtk::Application) and if yes have you some that you really would like in priority ? (both for gir_ffi or gir_ffi-gtk3).

**Comment by mvz** [comment]
Hi @cedlemo examples are definitely welcome, but I don't have any priority in mind. If anything is awkward to implement, please don't hesitate to open issues.

**Comment by mvz** [comment]
Hi @cedlemo, I just fixed the problem that made the empty callback proc necessary. Together with other changes in GirFFI, I can now condense the example into the following:

```ruby
require 'gir_ffi'
require 'gir_ffi-gtk3'
GirFFI.setup :Vte, '2.91'
GirFFI.setup :Gio
Gtk.init
win = Gtk::Window.new :toplevel
term = Vte::Terminal.new

win.add term
win.show_all
win.signal_connect('destroy') { Gtk.main_quit }

# Quit when the shell exits
term.signal_connect('eof') { Gtk.main_quit }

# Ask Vte for the user's shell
result, command_array = GLib.shell_parse_argv(Vte.get_user_shell)

result, pid = term.spawn_sync(:default,
                              "/home/matijs",
                              command_array,
                              [],
                              :search_path)

Gtk.main
```

Frankly, I'm not sure why the `Thread` part is no longer needed.

**Comment by cedlemo** [comment]
Hi @mvz,

> I can now condense the example into the following:

I have tried it, it works well and it is closer to the C api which let you create a `VteTerminal` without using threads .

> Hi @cedlemo examples are definitely welcome

I should be able to start creating some examples this week or the next week.

> If anything is awkward to implement, please don't hesitate to open issues.

Of course. Thanks
