### ISSUE TITLE
how should I set properties?

### ISSUE THREAD

**Issue by jcupitt** [mvz/gir_ffi#70]
Hi, in 0.7 I used to set properties like this:

```
irb(main):052:0> op = Vips::Operation.new "black"
=> #<Vips::Operation:0x0000000285a4b0 @struct=#<Vips::Operation::Struct:0x0000000285a410>>
irb(main):053:0> cls = GObject::object_class_from_instance op
=> #<GObject::ObjectClass:0x000000028433c8 @struct=#<GObject::ObjectClass::Struct:0x000000028433a0>>
irb(main):054:0> cls.list_properties.map {|x| x.get_name}
=> ["nickname", "description", "out", "width", "height", "bands"]
irb(main):055:0> op.set_property "width", 2
GirFFI::PropertyNotFoundError: Property 'width' not found in Vips::Operation
	from /home/john/packages/gems/gems/gir_ffi-0.9.5/lib/ffi-gobject/object.rb:120:in `property_param_spec'
```

I'm being dim, where has this has moved to in 0.9.5? I can't find it :(

**Comment by mvz** [comment]
I use a slightly different way to fetch the object class, and if I call `#list_properties` on that I only get 'nickname' and 'description'. Something odd is going on ...

**Comment by mvz** [comment]
Ah, it looks like the GObject class of `op` is not VipsOperation but VipsBlack. GirFFI doesn't take that possibility into account, but has started checking property names.

**Comment by mvz** [comment]
On further investigation, the problem is that I used to get the object class from the instance, and now I get it from the ruby class. This under the assumption that they would be the same for the result of calling a constructor.

**Comment by jcupitt** [comment]
That makes sense. Yes, I need a generic constructor, since I do my own introspection for subclasses of VipsOperation.

**Comment by mvz** [comment]
`Gio::File.new_for_path` does something similar, but is marked as a function instead of a constructor. Because of this, it actually returns a subclass in GirFFI. I'll investigate why the GIR reports different data for that one.

**Comment by mvz** [comment]
The reason this works for Gio::File is that Gio::File is an interface instead of a class. I'll take a look how e.g. pygi handles this.

**Comment by mvz** [comment]
It seems Python's GI implementation uses custom constructors that ignore the initializers, leaving them free to return any class. Also, Python allows changing an object's class which is not possible in Ruby. So, not much help there.

The quickest option for now is to add an override for `Vips::Operation.new`. Since it's the only GObject constructor I've seen that does not return an object of the stated type (apart from the special case `g_object_new`) I'm hesitant to provide generic support for that case.

The override would look like this:

```ruby
require 'gir_ffi'
GirFFI.setup :Vips

Vips.load_class :Operation

class Vips::Operation
  setup_method :new

  def self.new(name)
    _v2 = GirFFI::InPointer.from :utf8, name
    _v3 = Vips::Lib.vips_operation_new _v2
    _v1 = Vips::Operation.wrap(_v3)
    return _v1
  end
end
```

**Comment by jcupitt** [comment]
OK, thank you @mvz, I'll have a look into that. 

The `gobject-introspection` gem seems to allow `Vips::Operation.new` to return a subclass, I'm not sure how though. I get the list of support properties like this:

https://github.com/jcupitt/ruby-vips8/blob/master/lib/vips8/operation.rb#L8

And set a property like this:

https://github.com/jcupitt/ruby-vips8/blob/master/lib/vips8/argument.rb#L154

**Comment by jcupitt** [comment]
I had another thought: `VipsOperation` is an abstract class, perhaps `new` on an abstract class should be assumed to make some concrete subclass rather than the class itself?

**Comment by jcupitt** [comment]
\o/ thank you @mvz, it seems to work now.

```
john@kiwi:~/GIT/gir_ffi-vips (master)$ irb
irb(main):001:0> require 'vips8'
=> true
irb(main):002:0> op = Vips::Operation.new "black"
=> #<#<Class:0x00000001ca39a0>:0x00000001ca31d0 @struct=#<#<Class:0x00000001ca3838>:0x00000001ca31a8>>
irb(main):003:0> op.set_property "width", 2
=> nil
irb(main):004:0> op.get_property "width"
=> 2
```
