### ISSUE TITLE
Problem when embedding Ruby

### ISSUE THREAD

**Issue by kugel-** [mvz/gir_ffi#75]
See also https://github.com/ffi/ffi/issues/527. I'm not 100% sure where the appropriate place to discuss the problem is.

Anyway, I'm trying to embed ruby/gir_ffi in a native program. In this case I'm calling (via rb_require()) a ruby script that creates an object. That object in turn implements a callback (as in https://github.com/ffi/ffi/wiki/Callbacks).

So, the problem is: since I'm not calling the callback through a Ruby stack frame, rbffi thinks that I don't have the GIL (rbffi_frame_current() -> has_gvl is false). The callback invocation waits for some other thread to release it, which never happens. In short, I'm deadlocked inside callback_invoke().

As a hack, I can call rbffi_frame_push() through dlsym() (there is no deadlock if I do this) but I'm looking for a proper solution. What can you suggest?

My actual goal is to implement a libpeas loader for Ruby, so that plugins for a C prgram can be written in Ruby. This is largely making use of GObject introspetion.

**Comment by mvz** [comment]
I'm afraid there is not much that GirFFI can do about this.
