### ISSUE TITLE
User-defined class property with dash/underscore

### ISSUE THREAD

**Issue by kugel-** [mvz/gir_ffi#76]
Defining a property in a user-defined class that contains a dash leads to the following error:

/home/kugel/.gem/ruby/2.3.0/gems/gir_ffi-0.10.2/lib/gir_ffi/builders/user_defined_builder.rb:197:in `class_eval': (eval):1: syntax error, unexpected '-', expecting ';' or '\n' (SyntaxError)
        def property-name

This is because user_defined_builder.rb does class_eval to add accessors named after the property. But the canonical names of properties (with dashes) are invalid method names.

I find the following patch works but I'm not sure if it's enough:

```
diff --git a/lib/gir_ffi/builders/user_defined_builder.rb b/lib/gir_ffi/builders/user_defined_builder.rb
index 1a775c6..48937ab 100644
--- a/lib/gir_ffi/builders/user_defined_builder.rb
+++ b/lib/gir_ffi/builders/user_defined_builder.rb
@@ -184,7 +184,7 @@ module GirFFI
       end
 
       def setup_accessors_for_param_info(pinfo)
-        field_name = pinfo.name
+        field_name = pinfo.name.tr("-", "_")
         code = <<-CODE
         def #{field_name}
           @struct[:#{field_name}]
```

**Comment by mvz** [comment]
This is fixed in current master.

**Comment by kugel-** [comment]
Awesome! I'll give it a try

**Comment by kugel-** [comment]
I can confirm it works. Thank you.
