### ISSUE TITLE
Glib2 2.56 support

### ISSUE THREAD

**Issue by mbevc1** [mvz/gir_ffi#94]
Fedora 28 was released yesterday which is bumping `Glib2` to 2.56. Support was added in 0.12 release but we're pinning to `0.11.x` since we need Ruby 2.1 support. Can you branch 0.11 and I can submit `Glib2` support in?

**Comment by mbevc1** [comment]
Hey @mvz ! Thank for your response; use case here is we are bound to use older Ruby because other dependencies in the code. But development is done on modern platforms - Fedora28, and that breaks `iconv.rb` part of `gir_ffi`.

**Comment by mvz** [comment]
I see. I'm open to adding back Ruby 2.1 support to the 0.12 release if you can supply a pull request for that, since there should be nothing in the code that prevents that right now. However, 2.1 support will be removed again at some point so you should really get those dependencies updated or replaced.

**Comment by mvz** [comment]
I'll make a new release soon.

**Comment by mvz** [comment]
Version 0.12.1 with support for Ruby 2.1 and 2.2 has been released.

**Comment by mbevc1** [comment]
Oh, great - haven't got around to submit a similar PR. Thanks for releasing new version, I'll try that tomorrow.

**Comment by mbevc1** [comment]
Oh, just discovered there is a Ruby dep in gir_ffi-gnome_keyring 0.0.8 as well. Can you return Ruby 2.1 support there as well?

**Comment by mvz** [comment]
Ah yes, all dependent libraries have that :-). I'll update them as well.

**Comment by mvz** [comment]
@mbevc1 I've released a new version of `gir_ffi-gnome_keyring`.

**Comment by mbevc1** [comment]
Great, thanks @mvz ! Looks good now and we can use latest versions again :+1:
